[[redirects]]
  from = "/area-admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/area-admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/crea-lega"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/crea-lega/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 