[[redirects]]
  from = "/area-admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/area-admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/crea-lega"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/crea-lega/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/notifiche"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/notifiche/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/leghe"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/leghe/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/squadra/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/mercato"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/mercato/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/formazioni"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/formazioni/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/classifica"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/classifica/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profilo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profilo/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/super-admin-dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/super-admin-dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 