services:
  - type: web
    name: topleague-frontend
    env: static
    buildCommand: |
      pwd
      ls -la
      ls -la public/
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    routes:
      - type: rewrite
        source: /area-admin
        destination: /index.html
      - type: rewrite
        source: /area-admin/*
        destination: /index.html
      - type: rewrite
        source: /crea-lega
        destination: /index.html
      - type: rewrite
        source: /crea-lega/*
        destination: /index.html
      - type: rewrite
        source: /login
        destination: /index.html
      - type: rewrite
        source: /register
        destination: /index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /dashboard/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html 