#!/bin/bash

echo "🚀 MANUAL DEPLOYMENT INSTRUCTIONS"
echo "=================================="
echo ""
echo "Since SSH requires a password, please run these commands manually:"
echo ""
echo "1. First, copy the backend files:"
echo "   scp -r backend/* root@top-league.org:/var/www/top-league.org/backend/"
echo ""
echo "2. Copy the frontend build files:"
echo "   scp -r frontend/build/* root@top-league.org:/var/www/top-league.org/backend/public/"
echo ""
echo "3. Set proper permissions:"
echo "   ssh root@top-league.org 'chmod -R 755 /var/www/top-league.org/backend/public/'"
echo ""
echo "4. Restart the server:"
echo "   ssh root@top-league.org 'cd /var/www/top-league.org/backend && pkill -f node && sleep 3 && NODE_ENV=production pm2 start index.js --name topleague-backend'"
echo ""
echo "5. Test the deployment:"
echo "   curl -s https://top-league.org/api/ping"
echo ""
echo "✅ After running these commands, the site should work at: https://top-league.org" 