services:
  - type: web
    name: topleague-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html 