version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: topleague_postgres
    environment:
      POSTGRES_DB: topleague_db
      POSTGRES_USER: topleague_db_user
      POSTGRES_PASSWORD: topleague_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 